version: '3'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_PASSWORD: temppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: orenoid/telegram-account-bot
    restart: unless-stopped
    environment:
      MYSQL_DSN: root:temppassword@tcp(db:3306)/account?charset=utf8mb4&parseTime=True&loc=Local
      TELEBOT_TOKEN: YOUR_TELEBOT_TOKEN_HERE
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: