version: '3'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    env_file: "env/db.env"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  bot:
    image: orenoid/telegram-account-bot
    build:
      context: .
      dockerfile: bot.Dockerfile
    restart: unless-stopped
    env_file: "env/bot.env"
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    image: orenoid/telegram-account-bot-api
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: unless-stopped
    env_file: "env/api.env"
    ports:
      - "1323:1323"
    depends_on:
      - db
      - bot


volumes:
  db_data: