name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push Bot Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./bot.Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/telegram-account-bot:latest

      - name: Push Api Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./api.Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/telegram-account-bot-api:latest